### ISSUE TITLE
App is deployed to cloud but get errors when asking for results

### ISSUE THREAD

**Issue by PhilippeComte** [IBM/model-evaluation-workbench#9]
Hello , 
My lite account has a space in Dallas for Cloud foundry apps
The Studio instance is in London 
the NLC instance is in Germany .

I have managed to deploy the app to IBM Cloud and I get access to the main screen.
I click NLC , tick boxes for Model1 and model 2 
I can select the test file but then I click evalute performance , I get the message : 
**Error 500: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is com.ibm.watson.developer_cloud.service.exception.UnauthorizedException: Unauthorized: Access is denied due to invalid credentials. 
Tip: Did you set the Endpoint?**

I have assumed that the endpoint is the NLC service endpoint : here 
NLC_URL: https://gateway-fra.watsonplatform.net/natural-language-classifier/api
But maybe I'm wrong .
Any idea ?  Thanks in advance

**Comment by muralidharchavan** [comment]
Hello.
Seems like credentials are not correct. Can you confirm if you have updated manifest.yml file to include  NLC_API_KEY_CONFIG_1, NLC_CLASSIFIER_ID_CONFIG_1 values for first NLC instance and also NLC_API_KEY_CONFIG_2, NLC_CLASSIFIER_ID_CONFIG_2 for second NLC instance.

NLC_URL is correct. Also, these services being in different regions should not make any difference as long as we have the right urls.

**Comment by PhilippeComte** [comment]
Hello 
Thank you for contacting me. 
I have created 2 models in the same NLC in Frankfurt but Watson Studio is in London. It has created some issues already (incorrect credentials when trying to train a model entering the system via NLC service thru the Console.bluemix.net but ok when accessing the system thru Watson studio instance ... ) May be I face the same issue 
The apikey NLC_API_KEY_CONFIG_1 and the apykey NLC_API_KEY_CONFIG_2 are the same 
(NLC is not available in London) 

Is that ok ? See below 

Here is my manifest file 


applications: 
- path: target/workbenchModelEval.war 
memory: 512M 
instances: 1 
name: workbenchModelEval 
random-route: true 
disk_quota: 1024M 
env: 
NLC_API_KEY_CONFIG_1: nWPSwWpNwzGYpAw2jeof_EgFrp7788We0qWsC28Aq7cH 
NLC_CLASSIFIER_ID_CONFIG_1: 15348ax345-nlc-31 
NLC_API_KEY_CONFIG_2: nWPSwWpNwzGYpAw2jeof_EgFrp7788We0qWsC28Aq7cH 
NLC_CLASSIFIER_ID_CONFIG_2: 15348ax345-nlc-30 
NLC_URL: https://gateway-fra.watsonplatform.net/natural-language-classifier/api 

Cordialement 
Philippe Comte 
+33 676861847 

----- Mail original -----

De: "Muralidhar Chavan" <notifications@github.com> 
À: "IBM/model-evaluation-workbench" <model-evaluation-workbench@noreply.github.com> 
Cc: "Philippe Comte" <philippe_comte@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 27 Février 2019 07:22:58 
Objet: Re: [IBM/model-evaluation-workbench] App is deployed to cloud but get errors when asking for results (#9) 



Hello. 
Seems like credentials are not correct. Can you confirm if you have updated manifest.yml file to include NLC_API_KEY_CONFIG_1, NLC_CLASSIFIER_ID_CONFIG_1 values for first NLC instance and also NLC_API_KEY_CONFIG_2, NLC_CLASSIFIER_ID_CONFIG_2 for second NLC instance. 

NLC_URL is correct. Also, these services being in different regions should not make any difference as long as we have the right urls.

**Comment by PhilippeComte** [comment]
Hello , 

I 've made the app work on Watson Studio Dallas + NLC Dallas 

with the same kind of Manifest file as below 
So I think there is an issue with Studio in London and NLC in Frankfurt 

Cordialement 
Philippe Comte 
+33 676861847 

----- Mail original -----

De: "Muralidhar Chavan" <notifications@github.com> 
À: "IBM/model-evaluation-workbench" <model-evaluation-workbench@noreply.github.com> 
Cc: "Philippe Comte" <philippe_comte@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 27 Février 2019 07:22:58 
Objet: Re: [IBM/model-evaluation-workbench] App is deployed to cloud but get errors when asking for results (#9) 



Hello. 
Seems like credentials are not correct. Can you confirm if you have updated manifest.yml file to include NLC_API_KEY_CONFIG_1, NLC_CLASSIFIER_ID_CONFIG_1 values for first NLC instance and also NLC_API_KEY_CONFIG_2, NLC_CLASSIFIER_ID_CONFIG_2 for second NLC instance. 

NLC_URL is correct. Also, these services being in different regions should not make any difference as long as we have the right urls.

**Comment by muralidharchavan** [comment]
Hello. 
Ok, glad to know that you were able to get the application working. I have a question. What are you using Watson Studio for?

**Comment by PhilippeComte** [comment]
Hello , 

For the moment i'm just getting familiarized with the tool ... 

Cordialement 
Philippe Comte 
+33 676861847 

----- Mail original -----

De: "Muralidhar Chavan" <notifications@github.com> 
À: "IBM/model-evaluation-workbench" <model-evaluation-workbench@noreply.github.com> 
Cc: "Philippe Comte" <philippe_comte@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 27 Février 2019 11:33:48 
Objet: Re: [IBM/model-evaluation-workbench] App is deployed to cloud but get errors when asking for results (#9) 



Hello. 
Ok, glad to know that you were able to get the application working. I have a question. What are you using Watson Studio for?
